artsc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("user.urls")),
    path("social/",include("social.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views


app_name = "user"

urlpatterns = [
    path("",views.login_user,name="login"),
    path("register",views.register,name="register_user"),
    path("logout",views.logout_user,name="logout"),
    #APIs
    path("user/api/register/",views.register_user,name="api_user_register_api"),
    path("user/api/login/",views.Login.as_view(),name="api_user_login"),
    path("user/api/get_user_data/",views.get_user_data,name="api_get_user_data"),
    path("user/pi/change_profile_picture/",views.change_profile_picture,name="api_change_profile_picture"),
    path("user/api/get_logged_in_user",views.get_signedin_user,name="api_get_logged_in_user"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from  django.dispatch import receiver

from rest_framework.authtoken.models import Token

# Create your models here.
class User(AbstractUser):
    profile_photo = models.ImageField(upload_to='profile_pics',default='default.jpeg')
    def __str__(self) -> str:
        return self.email
    


@receiver(post_save,sender=User)
def create_token(sender,instance=None,created=False,**kwargs):
    print("Called")
    if created:
        Token.objects.create(user=instance)

user/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import authenticate,logout,login


from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token

from artsc.consts import Status
from social.models import Friend,Post
from social.serializers import PostSerializer

from .models import User
from .serializers import UserSerializer,GetUserSerializer
# Create your views here.

def login_user(request):
    if request.method =="POST":
        user = authenticate(username = request.POST.get('username'),password = request.POST.get("password"))

        if user is not None:
            login(request,user)
            return redirect(reverse("social:index"))
        else:
            return render(request,"user/login.html")
    return render(request,"user/login.html")


def register(request):
    if request.method == "POST":
        try:
            user = User(
            username = request.POST.get("username"),
            email = request.POST.get("email"),
            first_name = request.POST.get("first_name"),
            last_name = request.POST.get("last_name")
        )
            user.set_password(request.POST.get("password"))

            user.save()

            return redirect(reverse("user:login"))
            
        except Exception as e:
            return render(request,"user/register.html")

        

        user.save()

    return render(request,"user/register.html")


def logout_user(request):
    logout(request)
    return redirect(reverse("user:login"))


@api_view(["POST"])
def register_user(request):
    serializer = UserSerializer(data=request.data)

    if serializer.is_valid():
        try:
            user =serializer.save()
            
            return Response({
                "status":"successful",
                "username":user.username,
                "first_name":user.first_name,
                "last_name":user.last_name,
                "email":user.email,
                "profile_photo":user.profile_photo.url,
                "token":user.auth_token.key
            })
        except Exception as e:
            return Response({
                "status":Status.UNSUCCESSFUL,
                "error":e.__str__()
            })
    else:
        return Response({
            "status":Status.UNSUCCESSFUL,
            "error":"username already exists"
        })


class Login(ObtainAuthToken):


    def post(self, request, *args, **kwargs):
        context={}
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        if serializer.is_valid(raise_exception=False):
            user = serializer.validated_data['user']
            token, created = Token.objects.get_or_create(user=user)
            context['status']=Status.SUCCESSFUL
            context['token']=token.key
            context['email']=user.email
            context['first_name']=user.first_name
            context['last_name']=user.last_name
            context["profile_photo"] = user.profile_photo.url
            context["username"] = user.username

        else:
            context['status']=Status.UNSUCCESSFUL
            context["error"] = "Invalid Credentials"
        return Response(context)
    


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def get_user_data(request):
    try:
        user = User.objects.get(username = request.query_params.get("username"))
        posts = Post.objects.filter(user = user)
        post_serialzer = PostSerializer(posts,many = True)
        serializer = UserSerializer(user)
        friend = Friend.objects.filter(
            (Q(user1=user) & Q(user2=request.user)) |
            (Q(user1=request.user) & Q(user2=user))
        )
        if friend.count() > 0:
            if friend.first().accepted:
                friend_status = "FRIEND"
            else:
                friend_status = "SENT"
        else:
            if request.user.username == request.query_params.get("username"):
                friend_status = "NOT REQUIRED"
            else:   
                friend_status = "NOT A FRIEND"
        return Response({
            "status":Status.SUCCESSFUL,
            "user":serializer.data,
            "friend": friend_status,
            "posts":post_serialzer.data
        })
    
    except Exception as e:
        return Response({
            "status":Status.UNSUCCESSFUL,
            "error":e.__str__()
        })


@api_view(["POST"])
@permission_classes([IsAuthenticated])
def change_profile_picture(request):
    try:
        request.user.profile_photo = request.data.get("image")
        request.user.save()
    except Exception as e:
        return Response({
            "status":Status.UNSUCCESSFUL,
            "error": e.__str__()
        })

    return Response({
        "status":Status.SUCCESSFUL,
        "profile_photo":request.user.profile_photo.url
    })

@api_view(["GET"])
@permission_classes([IsAuthenticated])
def get_signedin_user(request):
    serializer = GetUserSerializer(request.user)
    posts = Post.objects.filter(user=request.user)
    post_serializer = PostSerializer(posts,many = True)

    return Response({
        "user":serializer.data,
        "posts": post_serializer.data
    })

user/templates/user/login.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Login</title>
		<link rel="stylesheet" href="{%static 'user/login-page.css'%}" />
		<!-- <script defer src="login-page.js"></script> -->
	</head>

	<body>
		<main id="main-holder">
			<h1 id="login-header">Login</h1>

			<img src="{%static 'logo.jpg'%}" style="width:30%" class="rounded mx-auto d-block" alt="...">

			<div id="login-error-msg-holder">
				<p id="login-error-msg">
					Invalid username
					<span id="error-msg-second-line">and/or password</span>
				</p>
			</div>

			<form method="post" id="login-form">
				{%csrf_token%}
				<input
					type="text"
					name="username"
					id="username-field"
					class="login-form-field"
					placeholder="Username"
				/>
				<input
					type="password"
					name="password"
					id="password-field"
					class="login-form-field"
					placeholder="Password"
				/>
				<button type="submit" id="login-form-submit" > Submit </button>
			</form>
			<a href="{%url 'user:register_user'%}">New user?</a>
		
		</main>
		
	</body>
</html>

user/templates/user/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Login</title>
		<link rel="stylesheet" href="{%static 'user/login-page.css' %}" />
	</head>

	<body>
		<main id="main-holder">
			<h1 id="login-header">Login</h1>
			<img src="{%static 'logo.jpg'%}" style="width:30%" class="rounded mx-auto d-block" alt="...">

			<div id="login-error-msg-holder">
				<p id="login-error-msg">
					Invalid username
					<span id="error-msg-second-line">and/or password</span>
				</p>
			</div>

			<form id="login-form" method="post">
				{%csrf_token%}
				<input
					type="text"
					name="username"
					id="username-field"
					class="login-form-field"
					placeholder="Username"
				/>
				<input
					type="text"
					name="first_name"
					id="username-field"
					class="login-form-field"
					placeholder="firstName"
				/>
				<input
					type="text"
					name="last_name"
					id="username-field"
					class="login-form-field"
					placeholder="lastName"
				/>
				<input
					type="email"
					name="email"
					id="username-field"
					class="login-form-field"
					placeholder="email"
				/>
				<input
					type="password"
					name="password"
					id="password-field"
					class="login-form-field"
					placeholder="Password"
				/>

				<button type="submit" id="login-form-submit">Submit</button>
			</form>
			<a href="{%url 'user:login'%}">Already a user?</a>
		</main>
	</body>
</html>